PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX mo: <http://purl.org/ontology/mo/>
PREFIX plo: <http://purl.org/net/po#>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX spo: <https://mini.pw.edu.pl/kg/spo#>

SELECT ?pl_id (SAMPLE(?name) as ?pl_name) (SAMPLE(?genre_name) as ?genre_name1) (SAMPLE(?subgenre_name) as ?subgenre_name1) (COUNT(?song_id) as ?song_count) WHERE {
  ?pl_id rdf:type plo:Playlist ;
       foaf:name ?name ;
       spo:genre ?genre ;
       spo:subgenre ?subgenre .
  ?genre foaf:name ?genre_name .
  ?subgenre foaf:name ?subgenre_name .
  
  ?song_id spo:playlist ?pl_id .
} 
GROUP BY ?pl_id
ORDER BY DESC(?song_count)
