PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX mo: <http://purl.org/ontology/mo/>
PREFIX plo: <http://purl.org/net/po#>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX spo: <https://mini.pw.edu.pl/kg/spo#>

SELECT (SAMPLE(?album_id) as ?album_id1) (SAMPLE(?album_name) as ?album_name1) (SAMPLE(?artist_name) as ?artist_name1) (SAMPLE(?releaseDate) as ?releaseDate1) (AVG(?popularity) as ?avg_popularity) WHERE {
	?album_id rdf:type mo:Record ;
           foaf:name ?album_name ;
           spo:releaseDate ?releaseDate .
  FILTER(?releaseDate > "2000-01-01"^^xsd:date && ?releaseDate < "2010-01-01"^^xsd:date)
  ?song_id rdf:type mo:Track ;
           spo:album ?album_id ;
           spo:artist ?artist_id ;
           spo:popularity ?popularity .
  ?artist_id foaf:name ?artist_name .
}
GROUP BY ?album_id 
ORDER BY DESC(?avg_popularity)