PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX mo: <http://purl.org/ontology/mo/>
PREFIX plo: <http://purl.org/net/po#>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX spo: <https://mini.pw.edu.pl/kg/spo#>

SELECT (SAMPLE(?song_id) as ?song_id1) (SAMPLE(?artist_name) as ?artist_name1) (COUNT(?playlist_id) as ?playlist_count) WHERE {
  ?song_id rdf:type mo:Track ;
           spo:playlist ?playlist_id ;
           spo:artist ?artist_id .
  ?artist_id foaf:name ?artist_name .
} 
GROUP BY ?song_id
ORDER BY DESC(?playlist_count)
